################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (11.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Source/FilteringFunctions/FilteringFunctions.c \
../Source/FilteringFunctions/FilteringFunctionsF16.c \
../Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../Source/FilteringFunctions/arm_biquad_cascade_df1_f16.c \
../Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.c \
../Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.c \
../Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.c \
../Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.c \
../Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.c \
../Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../Source/FilteringFunctions/arm_conv_f32.c \
../Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../Source/FilteringFunctions/arm_conv_fast_q15.c \
../Source/FilteringFunctions/arm_conv_fast_q31.c \
../Source/FilteringFunctions/arm_conv_opt_q15.c \
../Source/FilteringFunctions/arm_conv_opt_q7.c \
../Source/FilteringFunctions/arm_conv_partial_f32.c \
../Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../Source/FilteringFunctions/arm_conv_partial_q15.c \
../Source/FilteringFunctions/arm_conv_partial_q31.c \
../Source/FilteringFunctions/arm_conv_partial_q7.c \
../Source/FilteringFunctions/arm_conv_q15.c \
../Source/FilteringFunctions/arm_conv_q31.c \
../Source/FilteringFunctions/arm_conv_q7.c \
../Source/FilteringFunctions/arm_correlate_f16.c \
../Source/FilteringFunctions/arm_correlate_f32.c \
../Source/FilteringFunctions/arm_correlate_f64.c \
../Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../Source/FilteringFunctions/arm_correlate_fast_q15.c \
../Source/FilteringFunctions/arm_correlate_fast_q31.c \
../Source/FilteringFunctions/arm_correlate_opt_q15.c \
../Source/FilteringFunctions/arm_correlate_opt_q7.c \
../Source/FilteringFunctions/arm_correlate_q15.c \
../Source/FilteringFunctions/arm_correlate_q31.c \
../Source/FilteringFunctions/arm_correlate_q7.c \
../Source/FilteringFunctions/arm_fir_decimate_f32.c \
../Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../Source/FilteringFunctions/arm_fir_decimate_q15.c \
../Source/FilteringFunctions/arm_fir_decimate_q31.c \
../Source/FilteringFunctions/arm_fir_f16.c \
../Source/FilteringFunctions/arm_fir_f32.c \
../Source/FilteringFunctions/arm_fir_f64.c \
../Source/FilteringFunctions/arm_fir_fast_q15.c \
../Source/FilteringFunctions/arm_fir_fast_q31.c \
../Source/FilteringFunctions/arm_fir_init_f16.c \
../Source/FilteringFunctions/arm_fir_init_f32.c \
../Source/FilteringFunctions/arm_fir_init_f64.c \
../Source/FilteringFunctions/arm_fir_init_q15.c \
../Source/FilteringFunctions/arm_fir_init_q31.c \
../Source/FilteringFunctions/arm_fir_init_q7.c \
../Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../Source/FilteringFunctions/arm_fir_lattice_f32.c \
../Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../Source/FilteringFunctions/arm_fir_lattice_q15.c \
../Source/FilteringFunctions/arm_fir_lattice_q31.c \
../Source/FilteringFunctions/arm_fir_q15.c \
../Source/FilteringFunctions/arm_fir_q31.c \
../Source/FilteringFunctions/arm_fir_q7.c \
../Source/FilteringFunctions/arm_fir_sparse_f32.c \
../Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../Source/FilteringFunctions/arm_fir_sparse_q15.c \
../Source/FilteringFunctions/arm_fir_sparse_q31.c \
../Source/FilteringFunctions/arm_fir_sparse_q7.c \
../Source/FilteringFunctions/arm_iir_lattice_f32.c \
../Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../Source/FilteringFunctions/arm_iir_lattice_q15.c \
../Source/FilteringFunctions/arm_iir_lattice_q31.c \
../Source/FilteringFunctions/arm_levinson_durbin_f16.c \
../Source/FilteringFunctions/arm_levinson_durbin_f32.c \
../Source/FilteringFunctions/arm_levinson_durbin_q31.c \
../Source/FilteringFunctions/arm_lms_f32.c \
../Source/FilteringFunctions/arm_lms_init_f32.c \
../Source/FilteringFunctions/arm_lms_init_q15.c \
../Source/FilteringFunctions/arm_lms_init_q31.c \
../Source/FilteringFunctions/arm_lms_norm_f32.c \
../Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../Source/FilteringFunctions/arm_lms_norm_q15.c \
../Source/FilteringFunctions/arm_lms_norm_q31.c \
../Source/FilteringFunctions/arm_lms_q15.c \
../Source/FilteringFunctions/arm_lms_q31.c 

OBJS += \
./Source/FilteringFunctions/FilteringFunctions.o \
./Source/FilteringFunctions/FilteringFunctionsF16.o \
./Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o \
./Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o \
./Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o \
./Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o \
./Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o \
./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o \
./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./Source/FilteringFunctions/arm_conv_f32.o \
./Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./Source/FilteringFunctions/arm_conv_fast_q15.o \
./Source/FilteringFunctions/arm_conv_fast_q31.o \
./Source/FilteringFunctions/arm_conv_opt_q15.o \
./Source/FilteringFunctions/arm_conv_opt_q7.o \
./Source/FilteringFunctions/arm_conv_partial_f32.o \
./Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./Source/FilteringFunctions/arm_conv_partial_q15.o \
./Source/FilteringFunctions/arm_conv_partial_q31.o \
./Source/FilteringFunctions/arm_conv_partial_q7.o \
./Source/FilteringFunctions/arm_conv_q15.o \
./Source/FilteringFunctions/arm_conv_q31.o \
./Source/FilteringFunctions/arm_conv_q7.o \
./Source/FilteringFunctions/arm_correlate_f16.o \
./Source/FilteringFunctions/arm_correlate_f32.o \
./Source/FilteringFunctions/arm_correlate_f64.o \
./Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./Source/FilteringFunctions/arm_correlate_fast_q15.o \
./Source/FilteringFunctions/arm_correlate_fast_q31.o \
./Source/FilteringFunctions/arm_correlate_opt_q15.o \
./Source/FilteringFunctions/arm_correlate_opt_q7.o \
./Source/FilteringFunctions/arm_correlate_q15.o \
./Source/FilteringFunctions/arm_correlate_q31.o \
./Source/FilteringFunctions/arm_correlate_q7.o \
./Source/FilteringFunctions/arm_fir_decimate_f32.o \
./Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./Source/FilteringFunctions/arm_fir_decimate_q15.o \
./Source/FilteringFunctions/arm_fir_decimate_q31.o \
./Source/FilteringFunctions/arm_fir_f16.o \
./Source/FilteringFunctions/arm_fir_f32.o \
./Source/FilteringFunctions/arm_fir_f64.o \
./Source/FilteringFunctions/arm_fir_fast_q15.o \
./Source/FilteringFunctions/arm_fir_fast_q31.o \
./Source/FilteringFunctions/arm_fir_init_f16.o \
./Source/FilteringFunctions/arm_fir_init_f32.o \
./Source/FilteringFunctions/arm_fir_init_f64.o \
./Source/FilteringFunctions/arm_fir_init_q15.o \
./Source/FilteringFunctions/arm_fir_init_q31.o \
./Source/FilteringFunctions/arm_fir_init_q7.o \
./Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./Source/FilteringFunctions/arm_fir_lattice_f32.o \
./Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./Source/FilteringFunctions/arm_fir_lattice_q15.o \
./Source/FilteringFunctions/arm_fir_lattice_q31.o \
./Source/FilteringFunctions/arm_fir_q15.o \
./Source/FilteringFunctions/arm_fir_q31.o \
./Source/FilteringFunctions/arm_fir_q7.o \
./Source/FilteringFunctions/arm_fir_sparse_f32.o \
./Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./Source/FilteringFunctions/arm_fir_sparse_q15.o \
./Source/FilteringFunctions/arm_fir_sparse_q31.o \
./Source/FilteringFunctions/arm_fir_sparse_q7.o \
./Source/FilteringFunctions/arm_iir_lattice_f32.o \
./Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./Source/FilteringFunctions/arm_iir_lattice_q15.o \
./Source/FilteringFunctions/arm_iir_lattice_q31.o \
./Source/FilteringFunctions/arm_levinson_durbin_f16.o \
./Source/FilteringFunctions/arm_levinson_durbin_f32.o \
./Source/FilteringFunctions/arm_levinson_durbin_q31.o \
./Source/FilteringFunctions/arm_lms_f32.o \
./Source/FilteringFunctions/arm_lms_init_f32.o \
./Source/FilteringFunctions/arm_lms_init_q15.o \
./Source/FilteringFunctions/arm_lms_init_q31.o \
./Source/FilteringFunctions/arm_lms_norm_f32.o \
./Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./Source/FilteringFunctions/arm_lms_norm_q15.o \
./Source/FilteringFunctions/arm_lms_norm_q31.o \
./Source/FilteringFunctions/arm_lms_q15.o \
./Source/FilteringFunctions/arm_lms_q31.o 

C_DEPS += \
./Source/FilteringFunctions/FilteringFunctions.d \
./Source/FilteringFunctions/FilteringFunctionsF16.d \
./Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d \
./Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d \
./Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d \
./Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d \
./Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d \
./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d \
./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./Source/FilteringFunctions/arm_conv_f32.d \
./Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./Source/FilteringFunctions/arm_conv_fast_q15.d \
./Source/FilteringFunctions/arm_conv_fast_q31.d \
./Source/FilteringFunctions/arm_conv_opt_q15.d \
./Source/FilteringFunctions/arm_conv_opt_q7.d \
./Source/FilteringFunctions/arm_conv_partial_f32.d \
./Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./Source/FilteringFunctions/arm_conv_partial_q15.d \
./Source/FilteringFunctions/arm_conv_partial_q31.d \
./Source/FilteringFunctions/arm_conv_partial_q7.d \
./Source/FilteringFunctions/arm_conv_q15.d \
./Source/FilteringFunctions/arm_conv_q31.d \
./Source/FilteringFunctions/arm_conv_q7.d \
./Source/FilteringFunctions/arm_correlate_f16.d \
./Source/FilteringFunctions/arm_correlate_f32.d \
./Source/FilteringFunctions/arm_correlate_f64.d \
./Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./Source/FilteringFunctions/arm_correlate_fast_q15.d \
./Source/FilteringFunctions/arm_correlate_fast_q31.d \
./Source/FilteringFunctions/arm_correlate_opt_q15.d \
./Source/FilteringFunctions/arm_correlate_opt_q7.d \
./Source/FilteringFunctions/arm_correlate_q15.d \
./Source/FilteringFunctions/arm_correlate_q31.d \
./Source/FilteringFunctions/arm_correlate_q7.d \
./Source/FilteringFunctions/arm_fir_decimate_f32.d \
./Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./Source/FilteringFunctions/arm_fir_decimate_q15.d \
./Source/FilteringFunctions/arm_fir_decimate_q31.d \
./Source/FilteringFunctions/arm_fir_f16.d \
./Source/FilteringFunctions/arm_fir_f32.d \
./Source/FilteringFunctions/arm_fir_f64.d \
./Source/FilteringFunctions/arm_fir_fast_q15.d \
./Source/FilteringFunctions/arm_fir_fast_q31.d \
./Source/FilteringFunctions/arm_fir_init_f16.d \
./Source/FilteringFunctions/arm_fir_init_f32.d \
./Source/FilteringFunctions/arm_fir_init_f64.d \
./Source/FilteringFunctions/arm_fir_init_q15.d \
./Source/FilteringFunctions/arm_fir_init_q31.d \
./Source/FilteringFunctions/arm_fir_init_q7.d \
./Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./Source/FilteringFunctions/arm_fir_lattice_f32.d \
./Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./Source/FilteringFunctions/arm_fir_lattice_q15.d \
./Source/FilteringFunctions/arm_fir_lattice_q31.d \
./Source/FilteringFunctions/arm_fir_q15.d \
./Source/FilteringFunctions/arm_fir_q31.d \
./Source/FilteringFunctions/arm_fir_q7.d \
./Source/FilteringFunctions/arm_fir_sparse_f32.d \
./Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./Source/FilteringFunctions/arm_fir_sparse_q15.d \
./Source/FilteringFunctions/arm_fir_sparse_q31.d \
./Source/FilteringFunctions/arm_fir_sparse_q7.d \
./Source/FilteringFunctions/arm_iir_lattice_f32.d \
./Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./Source/FilteringFunctions/arm_iir_lattice_q15.d \
./Source/FilteringFunctions/arm_iir_lattice_q31.d \
./Source/FilteringFunctions/arm_levinson_durbin_f16.d \
./Source/FilteringFunctions/arm_levinson_durbin_f32.d \
./Source/FilteringFunctions/arm_levinson_durbin_q31.d \
./Source/FilteringFunctions/arm_lms_f32.d \
./Source/FilteringFunctions/arm_lms_init_f32.d \
./Source/FilteringFunctions/arm_lms_init_q15.d \
./Source/FilteringFunctions/arm_lms_init_q31.d \
./Source/FilteringFunctions/arm_lms_norm_f32.d \
./Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./Source/FilteringFunctions/arm_lms_norm_q15.d \
./Source/FilteringFunctions/arm_lms_norm_q31.d \
./Source/FilteringFunctions/arm_lms_q15.d \
./Source/FilteringFunctions/arm_lms_q31.d 


# Each subdirectory must supply rules for building sources it contributes
Source/FilteringFunctions/%.o Source/FilteringFunctions/%.su Source/FilteringFunctions/%.cyclo: ../Source/FilteringFunctions/%.c Source/FilteringFunctions/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32G474xx -c -I../Core/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc -I../Drivers/STM32G4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32G4xx/Include -I../Drivers/CMSIS/Include -I../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../Middlewares/Third_Party/ARM_CMSIS/PrivateInclude/ -I../Middlewares/Third_Party/ARM_CMSIS/Include/ -I../Middlewares/Third_Party/ARM_CMSIS/Include -I"C:/Users/User/Documents/GitHub/Class/Cl6/Source/BasicMathFunctions" -I"C:/Users/User/Documents/GitHub/Class/Cl6/Source/BayesFunctions" -I"C:/Users/User/Documents/GitHub/Class/Cl6/Source/CommonTables" -I"C:/Users/User/Documents/GitHub/Class/Cl6/Source/ComplexMathFunctions" -I"C:/Users/User/Documents/GitHub/Class/Cl6/Source/ControllerFunctions" -I"C:/Users/User/Documents/GitHub/Class/Cl6/Source/DistanceFunctions" -I"C:/Users/User/Documents/GitHub/Class/Cl6/Source/FastMathFunctions" -I"C:/Users/User/Documents/GitHub/Class/Cl6/Source/FilteringFunctions" -I"C:/Users/User/Documents/GitHub/Class/Cl6/Source/InterpolationFunctions" -I"C:/Users/User/Documents/GitHub/Class/Cl6/Source/MatrixFunctions" -I"C:/Users/User/Documents/GitHub/Class/Cl6/Source/QuaternionMathFunctions" -I"C:/Users/User/Documents/GitHub/Class/Cl6/Source/StatisticsFunctions" -I"C:/Users/User/Documents/GitHub/Class/Cl6/Source/SupportFunctions" -I"C:/Users/User/Documents/GitHub/Class/Cl6/Source/SVMFunctions" -I"C:/Users/User/Documents/GitHub/Class/Cl6/Source/TransformFunctions" -I"C:/Users/User/Documents/GitHub/Class/Cl6/Source/WindowFunctions" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Source-2f-FilteringFunctions

clean-Source-2f-FilteringFunctions:
	-$(RM) ./Source/FilteringFunctions/FilteringFunctions.cyclo ./Source/FilteringFunctions/FilteringFunctions.d ./Source/FilteringFunctions/FilteringFunctions.o ./Source/FilteringFunctions/FilteringFunctions.su ./Source/FilteringFunctions/FilteringFunctionsF16.cyclo ./Source/FilteringFunctions/FilteringFunctionsF16.d ./Source/FilteringFunctions/FilteringFunctionsF16.o ./Source/FilteringFunctions/FilteringFunctionsF16.su ./Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d ./Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o ./Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.su ./Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d ./Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o ./Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.su ./Source/FilteringFunctions/arm_biquad_cascade_df1_f16.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d ./Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o ./Source/FilteringFunctions/arm_biquad_cascade_df1_f16.su ./Source/FilteringFunctions/arm_biquad_cascade_df1_f32.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d ./Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o ./Source/FilteringFunctions/arm_biquad_cascade_df1_f32.su ./Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d ./Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o ./Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.su ./Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d ./Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o ./Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.su ./Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d ./Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o ./Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.su ./Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d ./Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o ./Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.su ./Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d ./Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o ./Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.su ./Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d ./Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o ./Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.su ./Source/FilteringFunctions/arm_biquad_cascade_df1_q15.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d ./Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o ./Source/FilteringFunctions/arm_biquad_cascade_df1_q15.su ./Source/FilteringFunctions/arm_biquad_cascade_df1_q31.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d ./Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o ./Source/FilteringFunctions/arm_biquad_cascade_df1_q31.su ./Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d ./Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o ./Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.su ./Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d ./Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o ./Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.su ./Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d ./Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o ./Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.su ./Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d ./Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o ./Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.su ./Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d ./Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o ./Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.su ./Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d ./Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o ./Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.su ./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d ./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o ./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.su ./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d ./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o ./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.su ./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d ./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o ./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.su ./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.cyclo ./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d ./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o ./Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.su
	-$(RM) ./Source/FilteringFunctions/arm_conv_f32.cyclo ./Source/FilteringFunctions/arm_conv_f32.d ./Source/FilteringFunctions/arm_conv_f32.o ./Source/FilteringFunctions/arm_conv_f32.su ./Source/FilteringFunctions/arm_conv_fast_opt_q15.cyclo ./Source/FilteringFunctions/arm_conv_fast_opt_q15.d ./Source/FilteringFunctions/arm_conv_fast_opt_q15.o ./Source/FilteringFunctions/arm_conv_fast_opt_q15.su ./Source/FilteringFunctions/arm_conv_fast_q15.cyclo ./Source/FilteringFunctions/arm_conv_fast_q15.d ./Source/FilteringFunctions/arm_conv_fast_q15.o ./Source/FilteringFunctions/arm_conv_fast_q15.su ./Source/FilteringFunctions/arm_conv_fast_q31.cyclo ./Source/FilteringFunctions/arm_conv_fast_q31.d ./Source/FilteringFunctions/arm_conv_fast_q31.o ./Source/FilteringFunctions/arm_conv_fast_q31.su ./Source/FilteringFunctions/arm_conv_opt_q15.cyclo ./Source/FilteringFunctions/arm_conv_opt_q15.d ./Source/FilteringFunctions/arm_conv_opt_q15.o ./Source/FilteringFunctions/arm_conv_opt_q15.su ./Source/FilteringFunctions/arm_conv_opt_q7.cyclo ./Source/FilteringFunctions/arm_conv_opt_q7.d ./Source/FilteringFunctions/arm_conv_opt_q7.o ./Source/FilteringFunctions/arm_conv_opt_q7.su ./Source/FilteringFunctions/arm_conv_partial_f32.cyclo ./Source/FilteringFunctions/arm_conv_partial_f32.d ./Source/FilteringFunctions/arm_conv_partial_f32.o ./Source/FilteringFunctions/arm_conv_partial_f32.su ./Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.cyclo ./Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d ./Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o ./Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.su ./Source/FilteringFunctions/arm_conv_partial_fast_q15.cyclo ./Source/FilteringFunctions/arm_conv_partial_fast_q15.d ./Source/FilteringFunctions/arm_conv_partial_fast_q15.o ./Source/FilteringFunctions/arm_conv_partial_fast_q15.su ./Source/FilteringFunctions/arm_conv_partial_fast_q31.cyclo ./Source/FilteringFunctions/arm_conv_partial_fast_q31.d ./Source/FilteringFunctions/arm_conv_partial_fast_q31.o ./Source/FilteringFunctions/arm_conv_partial_fast_q31.su ./Source/FilteringFunctions/arm_conv_partial_opt_q15.cyclo ./Source/FilteringFunctions/arm_conv_partial_opt_q15.d ./Source/FilteringFunctions/arm_conv_partial_opt_q15.o ./Source/FilteringFunctions/arm_conv_partial_opt_q15.su ./Source/FilteringFunctions/arm_conv_partial_opt_q7.cyclo ./Source/FilteringFunctions/arm_conv_partial_opt_q7.d ./Source/FilteringFunctions/arm_conv_partial_opt_q7.o ./Source/FilteringFunctions/arm_conv_partial_opt_q7.su ./Source/FilteringFunctions/arm_conv_partial_q15.cyclo ./Source/FilteringFunctions/arm_conv_partial_q15.d ./Source/FilteringFunctions/arm_conv_partial_q15.o ./Source/FilteringFunctions/arm_conv_partial_q15.su ./Source/FilteringFunctions/arm_conv_partial_q31.cyclo ./Source/FilteringFunctions/arm_conv_partial_q31.d ./Source/FilteringFunctions/arm_conv_partial_q31.o ./Source/FilteringFunctions/arm_conv_partial_q31.su ./Source/FilteringFunctions/arm_conv_partial_q7.cyclo ./Source/FilteringFunctions/arm_conv_partial_q7.d ./Source/FilteringFunctions/arm_conv_partial_q7.o ./Source/FilteringFunctions/arm_conv_partial_q7.su ./Source/FilteringFunctions/arm_conv_q15.cyclo ./Source/FilteringFunctions/arm_conv_q15.d ./Source/FilteringFunctions/arm_conv_q15.o ./Source/FilteringFunctions/arm_conv_q15.su ./Source/FilteringFunctions/arm_conv_q31.cyclo ./Source/FilteringFunctions/arm_conv_q31.d ./Source/FilteringFunctions/arm_conv_q31.o ./Source/FilteringFunctions/arm_conv_q31.su ./Source/FilteringFunctions/arm_conv_q7.cyclo ./Source/FilteringFunctions/arm_conv_q7.d ./Source/FilteringFunctions/arm_conv_q7.o ./Source/FilteringFunctions/arm_conv_q7.su ./Source/FilteringFunctions/arm_correlate_f16.cyclo ./Source/FilteringFunctions/arm_correlate_f16.d ./Source/FilteringFunctions/arm_correlate_f16.o ./Source/FilteringFunctions/arm_correlate_f16.su ./Source/FilteringFunctions/arm_correlate_f32.cyclo ./Source/FilteringFunctions/arm_correlate_f32.d ./Source/FilteringFunctions/arm_correlate_f32.o ./Source/FilteringFunctions/arm_correlate_f32.su ./Source/FilteringFunctions/arm_correlate_f64.cyclo ./Source/FilteringFunctions/arm_correlate_f64.d ./Source/FilteringFunctions/arm_correlate_f64.o ./Source/FilteringFunctions/arm_correlate_f64.su ./Source/FilteringFunctions/arm_correlate_fast_opt_q15.cyclo ./Source/FilteringFunctions/arm_correlate_fast_opt_q15.d ./Source/FilteringFunctions/arm_correlate_fast_opt_q15.o ./Source/FilteringFunctions/arm_correlate_fast_opt_q15.su ./Source/FilteringFunctions/arm_correlate_fast_q15.cyclo ./Source/FilteringFunctions/arm_correlate_fast_q15.d ./Source/FilteringFunctions/arm_correlate_fast_q15.o ./Source/FilteringFunctions/arm_correlate_fast_q15.su ./Source/FilteringFunctions/arm_correlate_fast_q31.cyclo ./Source/FilteringFunctions/arm_correlate_fast_q31.d ./Source/FilteringFunctions/arm_correlate_fast_q31.o ./Source/FilteringFunctions/arm_correlate_fast_q31.su ./Source/FilteringFunctions/arm_correlate_opt_q15.cyclo ./Source/FilteringFunctions/arm_correlate_opt_q15.d ./Source/FilteringFunctions/arm_correlate_opt_q15.o ./Source/FilteringFunctions/arm_correlate_opt_q15.su ./Source/FilteringFunctions/arm_correlate_opt_q7.cyclo ./Source/FilteringFunctions/arm_correlate_opt_q7.d ./Source/FilteringFunctions/arm_correlate_opt_q7.o ./Source/FilteringFunctions/arm_correlate_opt_q7.su ./Source/FilteringFunctions/arm_correlate_q15.cyclo ./Source/FilteringFunctions/arm_correlate_q15.d ./Source/FilteringFunctions/arm_correlate_q15.o ./Source/FilteringFunctions/arm_correlate_q15.su ./Source/FilteringFunctions/arm_correlate_q31.cyclo ./Source/FilteringFunctions/arm_correlate_q31.d ./Source/FilteringFunctions/arm_correlate_q31.o ./Source/FilteringFunctions/arm_correlate_q31.su ./Source/FilteringFunctions/arm_correlate_q7.cyclo ./Source/FilteringFunctions/arm_correlate_q7.d ./Source/FilteringFunctions/arm_correlate_q7.o ./Source/FilteringFunctions/arm_correlate_q7.su
	-$(RM) ./Source/FilteringFunctions/arm_fir_decimate_f32.cyclo ./Source/FilteringFunctions/arm_fir_decimate_f32.d ./Source/FilteringFunctions/arm_fir_decimate_f32.o ./Source/FilteringFunctions/arm_fir_decimate_f32.su ./Source/FilteringFunctions/arm_fir_decimate_fast_q15.cyclo ./Source/FilteringFunctions/arm_fir_decimate_fast_q15.d ./Source/FilteringFunctions/arm_fir_decimate_fast_q15.o ./Source/FilteringFunctions/arm_fir_decimate_fast_q15.su ./Source/FilteringFunctions/arm_fir_decimate_fast_q31.cyclo ./Source/FilteringFunctions/arm_fir_decimate_fast_q31.d ./Source/FilteringFunctions/arm_fir_decimate_fast_q31.o ./Source/FilteringFunctions/arm_fir_decimate_fast_q31.su ./Source/FilteringFunctions/arm_fir_decimate_init_f32.cyclo ./Source/FilteringFunctions/arm_fir_decimate_init_f32.d ./Source/FilteringFunctions/arm_fir_decimate_init_f32.o ./Source/FilteringFunctions/arm_fir_decimate_init_f32.su ./Source/FilteringFunctions/arm_fir_decimate_init_q15.cyclo ./Source/FilteringFunctions/arm_fir_decimate_init_q15.d ./Source/FilteringFunctions/arm_fir_decimate_init_q15.o ./Source/FilteringFunctions/arm_fir_decimate_init_q15.su ./Source/FilteringFunctions/arm_fir_decimate_init_q31.cyclo ./Source/FilteringFunctions/arm_fir_decimate_init_q31.d ./Source/FilteringFunctions/arm_fir_decimate_init_q31.o ./Source/FilteringFunctions/arm_fir_decimate_init_q31.su ./Source/FilteringFunctions/arm_fir_decimate_q15.cyclo ./Source/FilteringFunctions/arm_fir_decimate_q15.d ./Source/FilteringFunctions/arm_fir_decimate_q15.o ./Source/FilteringFunctions/arm_fir_decimate_q15.su ./Source/FilteringFunctions/arm_fir_decimate_q31.cyclo ./Source/FilteringFunctions/arm_fir_decimate_q31.d ./Source/FilteringFunctions/arm_fir_decimate_q31.o ./Source/FilteringFunctions/arm_fir_decimate_q31.su ./Source/FilteringFunctions/arm_fir_f16.cyclo ./Source/FilteringFunctions/arm_fir_f16.d ./Source/FilteringFunctions/arm_fir_f16.o ./Source/FilteringFunctions/arm_fir_f16.su ./Source/FilteringFunctions/arm_fir_f32.cyclo ./Source/FilteringFunctions/arm_fir_f32.d ./Source/FilteringFunctions/arm_fir_f32.o ./Source/FilteringFunctions/arm_fir_f32.su ./Source/FilteringFunctions/arm_fir_f64.cyclo ./Source/FilteringFunctions/arm_fir_f64.d ./Source/FilteringFunctions/arm_fir_f64.o ./Source/FilteringFunctions/arm_fir_f64.su ./Source/FilteringFunctions/arm_fir_fast_q15.cyclo ./Source/FilteringFunctions/arm_fir_fast_q15.d ./Source/FilteringFunctions/arm_fir_fast_q15.o ./Source/FilteringFunctions/arm_fir_fast_q15.su ./Source/FilteringFunctions/arm_fir_fast_q31.cyclo ./Source/FilteringFunctions/arm_fir_fast_q31.d ./Source/FilteringFunctions/arm_fir_fast_q31.o ./Source/FilteringFunctions/arm_fir_fast_q31.su ./Source/FilteringFunctions/arm_fir_init_f16.cyclo ./Source/FilteringFunctions/arm_fir_init_f16.d ./Source/FilteringFunctions/arm_fir_init_f16.o ./Source/FilteringFunctions/arm_fir_init_f16.su ./Source/FilteringFunctions/arm_fir_init_f32.cyclo ./Source/FilteringFunctions/arm_fir_init_f32.d ./Source/FilteringFunctions/arm_fir_init_f32.o ./Source/FilteringFunctions/arm_fir_init_f32.su ./Source/FilteringFunctions/arm_fir_init_f64.cyclo ./Source/FilteringFunctions/arm_fir_init_f64.d ./Source/FilteringFunctions/arm_fir_init_f64.o ./Source/FilteringFunctions/arm_fir_init_f64.su ./Source/FilteringFunctions/arm_fir_init_q15.cyclo ./Source/FilteringFunctions/arm_fir_init_q15.d ./Source/FilteringFunctions/arm_fir_init_q15.o ./Source/FilteringFunctions/arm_fir_init_q15.su ./Source/FilteringFunctions/arm_fir_init_q31.cyclo ./Source/FilteringFunctions/arm_fir_init_q31.d ./Source/FilteringFunctions/arm_fir_init_q31.o ./Source/FilteringFunctions/arm_fir_init_q31.su ./Source/FilteringFunctions/arm_fir_init_q7.cyclo ./Source/FilteringFunctions/arm_fir_init_q7.d ./Source/FilteringFunctions/arm_fir_init_q7.o ./Source/FilteringFunctions/arm_fir_init_q7.su ./Source/FilteringFunctions/arm_fir_interpolate_f32.cyclo ./Source/FilteringFunctions/arm_fir_interpolate_f32.d ./Source/FilteringFunctions/arm_fir_interpolate_f32.o ./Source/FilteringFunctions/arm_fir_interpolate_f32.su ./Source/FilteringFunctions/arm_fir_interpolate_init_f32.cyclo ./Source/FilteringFunctions/arm_fir_interpolate_init_f32.d ./Source/FilteringFunctions/arm_fir_interpolate_init_f32.o ./Source/FilteringFunctions/arm_fir_interpolate_init_f32.su ./Source/FilteringFunctions/arm_fir_interpolate_init_q15.cyclo ./Source/FilteringFunctions/arm_fir_interpolate_init_q15.d ./Source/FilteringFunctions/arm_fir_interpolate_init_q15.o ./Source/FilteringFunctions/arm_fir_interpolate_init_q15.su ./Source/FilteringFunctions/arm_fir_interpolate_init_q31.cyclo ./Source/FilteringFunctions/arm_fir_interpolate_init_q31.d ./Source/FilteringFunctions/arm_fir_interpolate_init_q31.o ./Source/FilteringFunctions/arm_fir_interpolate_init_q31.su ./Source/FilteringFunctions/arm_fir_interpolate_q15.cyclo ./Source/FilteringFunctions/arm_fir_interpolate_q15.d ./Source/FilteringFunctions/arm_fir_interpolate_q15.o ./Source/FilteringFunctions/arm_fir_interpolate_q15.su ./Source/FilteringFunctions/arm_fir_interpolate_q31.cyclo ./Source/FilteringFunctions/arm_fir_interpolate_q31.d ./Source/FilteringFunctions/arm_fir_interpolate_q31.o ./Source/FilteringFunctions/arm_fir_interpolate_q31.su ./Source/FilteringFunctions/arm_fir_lattice_f32.cyclo ./Source/FilteringFunctions/arm_fir_lattice_f32.d ./Source/FilteringFunctions/arm_fir_lattice_f32.o ./Source/FilteringFunctions/arm_fir_lattice_f32.su ./Source/FilteringFunctions/arm_fir_lattice_init_f32.cyclo ./Source/FilteringFunctions/arm_fir_lattice_init_f32.d ./Source/FilteringFunctions/arm_fir_lattice_init_f32.o ./Source/FilteringFunctions/arm_fir_lattice_init_f32.su ./Source/FilteringFunctions/arm_fir_lattice_init_q15.cyclo ./Source/FilteringFunctions/arm_fir_lattice_init_q15.d ./Source/FilteringFunctions/arm_fir_lattice_init_q15.o ./Source/FilteringFunctions/arm_fir_lattice_init_q15.su ./Source/FilteringFunctions/arm_fir_lattice_init_q31.cyclo ./Source/FilteringFunctions/arm_fir_lattice_init_q31.d
	-$(RM) ./Source/FilteringFunctions/arm_fir_lattice_init_q31.o ./Source/FilteringFunctions/arm_fir_lattice_init_q31.su ./Source/FilteringFunctions/arm_fir_lattice_q15.cyclo ./Source/FilteringFunctions/arm_fir_lattice_q15.d ./Source/FilteringFunctions/arm_fir_lattice_q15.o ./Source/FilteringFunctions/arm_fir_lattice_q15.su ./Source/FilteringFunctions/arm_fir_lattice_q31.cyclo ./Source/FilteringFunctions/arm_fir_lattice_q31.d ./Source/FilteringFunctions/arm_fir_lattice_q31.o ./Source/FilteringFunctions/arm_fir_lattice_q31.su ./Source/FilteringFunctions/arm_fir_q15.cyclo ./Source/FilteringFunctions/arm_fir_q15.d ./Source/FilteringFunctions/arm_fir_q15.o ./Source/FilteringFunctions/arm_fir_q15.su ./Source/FilteringFunctions/arm_fir_q31.cyclo ./Source/FilteringFunctions/arm_fir_q31.d ./Source/FilteringFunctions/arm_fir_q31.o ./Source/FilteringFunctions/arm_fir_q31.su ./Source/FilteringFunctions/arm_fir_q7.cyclo ./Source/FilteringFunctions/arm_fir_q7.d ./Source/FilteringFunctions/arm_fir_q7.o ./Source/FilteringFunctions/arm_fir_q7.su ./Source/FilteringFunctions/arm_fir_sparse_f32.cyclo ./Source/FilteringFunctions/arm_fir_sparse_f32.d ./Source/FilteringFunctions/arm_fir_sparse_f32.o ./Source/FilteringFunctions/arm_fir_sparse_f32.su ./Source/FilteringFunctions/arm_fir_sparse_init_f32.cyclo ./Source/FilteringFunctions/arm_fir_sparse_init_f32.d ./Source/FilteringFunctions/arm_fir_sparse_init_f32.o ./Source/FilteringFunctions/arm_fir_sparse_init_f32.su ./Source/FilteringFunctions/arm_fir_sparse_init_q15.cyclo ./Source/FilteringFunctions/arm_fir_sparse_init_q15.d ./Source/FilteringFunctions/arm_fir_sparse_init_q15.o ./Source/FilteringFunctions/arm_fir_sparse_init_q15.su ./Source/FilteringFunctions/arm_fir_sparse_init_q31.cyclo ./Source/FilteringFunctions/arm_fir_sparse_init_q31.d ./Source/FilteringFunctions/arm_fir_sparse_init_q31.o ./Source/FilteringFunctions/arm_fir_sparse_init_q31.su ./Source/FilteringFunctions/arm_fir_sparse_init_q7.cyclo ./Source/FilteringFunctions/arm_fir_sparse_init_q7.d ./Source/FilteringFunctions/arm_fir_sparse_init_q7.o ./Source/FilteringFunctions/arm_fir_sparse_init_q7.su ./Source/FilteringFunctions/arm_fir_sparse_q15.cyclo ./Source/FilteringFunctions/arm_fir_sparse_q15.d ./Source/FilteringFunctions/arm_fir_sparse_q15.o ./Source/FilteringFunctions/arm_fir_sparse_q15.su ./Source/FilteringFunctions/arm_fir_sparse_q31.cyclo ./Source/FilteringFunctions/arm_fir_sparse_q31.d ./Source/FilteringFunctions/arm_fir_sparse_q31.o ./Source/FilteringFunctions/arm_fir_sparse_q31.su ./Source/FilteringFunctions/arm_fir_sparse_q7.cyclo ./Source/FilteringFunctions/arm_fir_sparse_q7.d ./Source/FilteringFunctions/arm_fir_sparse_q7.o ./Source/FilteringFunctions/arm_fir_sparse_q7.su ./Source/FilteringFunctions/arm_iir_lattice_f32.cyclo ./Source/FilteringFunctions/arm_iir_lattice_f32.d ./Source/FilteringFunctions/arm_iir_lattice_f32.o ./Source/FilteringFunctions/arm_iir_lattice_f32.su ./Source/FilteringFunctions/arm_iir_lattice_init_f32.cyclo ./Source/FilteringFunctions/arm_iir_lattice_init_f32.d ./Source/FilteringFunctions/arm_iir_lattice_init_f32.o ./Source/FilteringFunctions/arm_iir_lattice_init_f32.su ./Source/FilteringFunctions/arm_iir_lattice_init_q15.cyclo ./Source/FilteringFunctions/arm_iir_lattice_init_q15.d ./Source/FilteringFunctions/arm_iir_lattice_init_q15.o ./Source/FilteringFunctions/arm_iir_lattice_init_q15.su ./Source/FilteringFunctions/arm_iir_lattice_init_q31.cyclo ./Source/FilteringFunctions/arm_iir_lattice_init_q31.d ./Source/FilteringFunctions/arm_iir_lattice_init_q31.o ./Source/FilteringFunctions/arm_iir_lattice_init_q31.su ./Source/FilteringFunctions/arm_iir_lattice_q15.cyclo ./Source/FilteringFunctions/arm_iir_lattice_q15.d ./Source/FilteringFunctions/arm_iir_lattice_q15.o ./Source/FilteringFunctions/arm_iir_lattice_q15.su ./Source/FilteringFunctions/arm_iir_lattice_q31.cyclo ./Source/FilteringFunctions/arm_iir_lattice_q31.d ./Source/FilteringFunctions/arm_iir_lattice_q31.o ./Source/FilteringFunctions/arm_iir_lattice_q31.su ./Source/FilteringFunctions/arm_levinson_durbin_f16.cyclo ./Source/FilteringFunctions/arm_levinson_durbin_f16.d ./Source/FilteringFunctions/arm_levinson_durbin_f16.o ./Source/FilteringFunctions/arm_levinson_durbin_f16.su ./Source/FilteringFunctions/arm_levinson_durbin_f32.cyclo ./Source/FilteringFunctions/arm_levinson_durbin_f32.d ./Source/FilteringFunctions/arm_levinson_durbin_f32.o ./Source/FilteringFunctions/arm_levinson_durbin_f32.su ./Source/FilteringFunctions/arm_levinson_durbin_q31.cyclo ./Source/FilteringFunctions/arm_levinson_durbin_q31.d ./Source/FilteringFunctions/arm_levinson_durbin_q31.o ./Source/FilteringFunctions/arm_levinson_durbin_q31.su ./Source/FilteringFunctions/arm_lms_f32.cyclo ./Source/FilteringFunctions/arm_lms_f32.d ./Source/FilteringFunctions/arm_lms_f32.o ./Source/FilteringFunctions/arm_lms_f32.su ./Source/FilteringFunctions/arm_lms_init_f32.cyclo ./Source/FilteringFunctions/arm_lms_init_f32.d ./Source/FilteringFunctions/arm_lms_init_f32.o ./Source/FilteringFunctions/arm_lms_init_f32.su ./Source/FilteringFunctions/arm_lms_init_q15.cyclo ./Source/FilteringFunctions/arm_lms_init_q15.d ./Source/FilteringFunctions/arm_lms_init_q15.o ./Source/FilteringFunctions/arm_lms_init_q15.su ./Source/FilteringFunctions/arm_lms_init_q31.cyclo ./Source/FilteringFunctions/arm_lms_init_q31.d ./Source/FilteringFunctions/arm_lms_init_q31.o ./Source/FilteringFunctions/arm_lms_init_q31.su ./Source/FilteringFunctions/arm_lms_norm_f32.cyclo ./Source/FilteringFunctions/arm_lms_norm_f32.d ./Source/FilteringFunctions/arm_lms_norm_f32.o ./Source/FilteringFunctions/arm_lms_norm_f32.su ./Source/FilteringFunctions/arm_lms_norm_init_f32.cyclo ./Source/FilteringFunctions/arm_lms_norm_init_f32.d ./Source/FilteringFunctions/arm_lms_norm_init_f32.o ./Source/FilteringFunctions/arm_lms_norm_init_f32.su ./Source/FilteringFunctions/arm_lms_norm_init_q15.cyclo ./Source/FilteringFunctions/arm_lms_norm_init_q15.d ./Source/FilteringFunctions/arm_lms_norm_init_q15.o
	-$(RM) ./Source/FilteringFunctions/arm_lms_norm_init_q15.su ./Source/FilteringFunctions/arm_lms_norm_init_q31.cyclo ./Source/FilteringFunctions/arm_lms_norm_init_q31.d ./Source/FilteringFunctions/arm_lms_norm_init_q31.o ./Source/FilteringFunctions/arm_lms_norm_init_q31.su ./Source/FilteringFunctions/arm_lms_norm_q15.cyclo ./Source/FilteringFunctions/arm_lms_norm_q15.d ./Source/FilteringFunctions/arm_lms_norm_q15.o ./Source/FilteringFunctions/arm_lms_norm_q15.su ./Source/FilteringFunctions/arm_lms_norm_q31.cyclo ./Source/FilteringFunctions/arm_lms_norm_q31.d ./Source/FilteringFunctions/arm_lms_norm_q31.o ./Source/FilteringFunctions/arm_lms_norm_q31.su ./Source/FilteringFunctions/arm_lms_q15.cyclo ./Source/FilteringFunctions/arm_lms_q15.d ./Source/FilteringFunctions/arm_lms_q15.o ./Source/FilteringFunctions/arm_lms_q15.su ./Source/FilteringFunctions/arm_lms_q31.cyclo ./Source/FilteringFunctions/arm_lms_q31.d ./Source/FilteringFunctions/arm_lms_q31.o ./Source/FilteringFunctions/arm_lms_q31.su

.PHONY: clean-Source-2f-FilteringFunctions

